<?php
	//定义数据库相关的配置信息
	define('DB_HOST','localhost');
	define('DB_USER','root');
	define('DB_PWD','');
	define('CHARSET','utf8');
	define('DB_NAME','project');
	define('DB_PREFIX','');
	//设置时区
	date_default_timezone_set('PRC');